### ISSUE TITLE
Need updated .sql file

### ISSUE THREAD

**Issue by codemasterkarol** [TheGamesDB/TheGamesDB#162]
Hey -- the dev pack includes a sql file from March 2013. Any chance we could get an updated one please? I went to pull some games for Atari 2600 and it's missing over 200 games from the current listing.

**Comment by flexage** [comment]
Hi there.... sorry for the slow reply, this project has been running on silent for a while.

Just for any further information, the dev pack is simply a selection of sample data/imagery which the community can use to contribute to development of thegamesdb.net. It is not a full data dump, and is unlikely to become one.

The preferred course of action for third-party apps to request data from our database is via our API
