### ISSUE TITLE
how to creat search form

### ISSUE THREAD

**Issue by BanShee8** [TheGamesDB/TheGamesDB#170]
hi i want make a wordpress plugin for call back game data in this site like gamesport site and other bigest site now problem is i cant creat a search form i creat this following code's but not a resualt
<?php
$q=$_GET["name"];
$keyword=strtoupper($q);
$xml=simplexml_load_file("http://thegamesdb.net/api/GetGamesList.php?name=");
foreach ($xml->Game as $item) {
    $title = (string) $item->GameTitle;
$title2=strtoupper($title);	
$strpos = strpos($title2, $keyword);
if($strpos == TRUE){
echo $title;
echo "<br/>";
}
}
?>

call back in ajax:
function showResult(str)
{
if (str.length==0)
  {
  document.getElementById("livesearch").innerHTML="";
  document.getElementById("livesearch").style.border="0px";
  return;
  }
if (window.XMLHttpRequest)
  {// code for IE7+, Firefox, Chrome, Opera, Safari
  xmlhttp=new XMLHttpRequest();
  }
else
  {// code for IE6, IE5
  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
xmlhttp.onreadystatechange=function()
  {
  if (xmlhttp.readyState==4 && xmlhttp.status==200)
    {
    document.getElementById("livesearch").innerHTML=xmlhttp.responseText;
    document.getElementById("livesearch").style.border="1px solid #A5ACB2";
    }
  }
xmlhttp.open("GET","ajax-php-search.php?name="+str,true);
xmlhttp.send();
}

form
input type="text" size="30" onkeyup="showResult(this.value)"
div id="livesearch" /div
/form
pls help me to fix it
i remove html tag here to can see it

**Comment by flexage** [comment]
Hi there, you have provided us with a code exampe, which is good, but you have not told us what the exact problem or error is that you've been getting?

Does the PHP script manage to retrieve the data properly, and are you able to echo it out?

If so them maybe your Javascript AJAX may be faulty, have you considered returning your PHP data in JSON format  - json_encode() - and then using jQuery's .ajax() method in your JS to automatically parse your json results into an array of JS objects?

That's the way I'd be doing it :wink:

**Comment by BanShee8** [comment]
hi thanks for anwser i made it now :) just have 1 qustion how i can retrive all cosol for 1 game? like 
Witcher 3=PC,XBOXONE,PS4 but in your xml's just show 1 platform in platform area can i retrive all?

**Comment by flexage** [comment]
Hi BanShee8,

I'm glad you managed to make it.

Unfortunately we don't yet have a way to get all platforms for a game, although it's possible we may do in the future.
