### ISSUE TITLE
Everything offline/down?

### ISSUE THREAD

**Issue by jonbarrow** [TheGamesDB/TheGamesDB#185]
The site has been down for over a day (according to http://www.isitdownrightnow.com it's been down for over a week, but I was able to connect to it around 3 days ago). There hasn't been very much activity here either lately, and there was no mention of any downtime on the Facebook or Twitter. I tried contacting thegamesdb on both Facebook and Twitter to find out about the week-long outage and haven't heard anything back.

I have an application that was relying on thegamesdb and has now become completely unusable for new users (old users of it still have some data cached but new users aren't able to do anything). Does anyone have any more information on the outage? Is this entire thing dead now?  With everything being down, it also means the forums are down so there's nowhere else to post this. It also means I can't download the dev-pack, so I can't host a copy of the database locally. Does anyone possibly have an online mirror of either the whole site or at least the dev pack?

**Comment by flexage** [comment]
@RedDuckss thanks for bringing this to our attention.

I have fixed the issue that was causing the site to be unavailable. It's a little slow at the minute, but performance should return as traffic stabilizes and the cache is rebuilt.

The facebook and twitter accounts are largely un-monitored, and are just used for posting information as and when they're needed.

We do have alerts in place to notify us of any downtime, but on this occasion they failed to fire.

We do our best to keep the site available at all times, but we are a small 2-man team who need to work day jobs, sleep, and have families - sometimes things will just slip through the net.

Again, thanks for the heads-up :+1:
