### ISSUE TITLE
TheGamesDB not available/working on RetroPie durring scrape process 

### ISSUE THREAD

**Issue by ghost** [TheGamesDB/TheGamesDB#191]
Raspberry Pi 4
RetroPie 4.7.11

I dont know if it is down but im not able to scrape games from your database.

**Comment by theofficialgman** [comment]
I also am unable to scrape or access https://thegamesdb.net/

**Comment by ghost** [comment]
Im not sure if it is down, I don't want to have to go with the hassle of making a account just to contact them, making accounts is a annoyance that cant be helped with disposable emails part of the time.

In the meantime you can try ScreenScraper, it was acting up earlier last week but it did improve.

**Comment by ghost** [comment]
I tested at a later date to see that now TheGamesDB works and then the alternative was one that was not working. I will close this issue for now.
